#ifndef CONSTANTS_H
#define CONSTANTS_H

#define API_BASE_URL "https://tweeta.tiago.zip/api"
#define BASE_DOMAIN "https://tweeta.tiago.zip"

#define AVATAR_SIZE 48
#define MEDIA_SIZE 400

#define PUBLIC_TWEETS_URL API_BASE_URL "/public-tweets"
#define TIMELINE_URL API_BASE_URL "/timeline/"
#define LOGIN_URL API_BASE_URL "/auth/basic-login"
#define AUTH_ME_URL API_BASE_URL "/auth/me"
#define AUTH_PASSKEYS_URL API_BASE_URL "/auth/passkeys"
#define AUTH_PASSKEY_NAME_URL API_BASE_URL "/auth/passkeys/%s/name"
#define AUTH_PASSKEY_DELETE_URL API_BASE_URL "/auth/passkeys/%s"
#define AUTH_PASSKEY_GENERATE_REGISTRATION_URL API_BASE_URL "/auth/generate-registration-options"
#define AUTH_PASSKEY_VERIFY_REGISTRATION_URL API_BASE_URL "/auth/verify-registration"
#define AUTH_PASSKEY_GENERATE_AUTHENTICATION_URL API_BASE_URL "/auth/generate-authentication-options"
#define AUTH_PASSKEY_VERIFY_AUTHENTICATION_URL API_BASE_URL "/auth/verify-authentication"
#define AUTH_REGISTER_PASSWORD_URL API_BASE_URL "/auth/register-with-password"
#define AUTH_USERNAME_AVAILABILITY_URL API_BASE_URL "/auth/username-availability"
#define AUTH_MODERATION_HISTORY_URL API_BASE_URL "/auth/moderation-history"
#define AUTH_VALIDATE_ACCOUNTS_URL API_BASE_URL "/auth/validate-accounts"
#define AUTH_SWITCH_DELEGATE_URL API_BASE_URL "/auth/switch-to-delegate"
#define AUTH_SWITCH_PRIMARY_URL API_BASE_URL "/auth/switch-to-primary"
#define AUTH_ADD_ACCOUNT_URL API_BASE_URL "/auth/add-account"
#define POST_TWEET_URL API_BASE_URL "/tweets/"
#define TWEET_DETAILS_URL API_BASE_URL "/tweets/%s"
#define TWEET_LIKES_URL API_BASE_URL "/tweets/%s/likes"
#define TWEET_RETWEETS_URL API_BASE_URL "/tweets/%s/retweets"
#define TWEET_QUOTES_URL API_BASE_URL "/tweets/%s/quotes"
#define TWEET_REACTIONS_URL API_BASE_URL "/tweets/%s/reactions"
#define TWEET_CAN_REPLY_URL API_BASE_URL "/tweets/can-reply/%s"
#define TWEET_BULK_DELETE_URL API_BASE_URL "/tweets/bulk-delete"
#define TWEET_EDIT_URL API_BASE_URL "/tweets/%s"
#define TWEET_EDIT_HISTORY_URL API_BASE_URL "/tweets/%s/edit-history"
#define TWEET_DELETE_URL API_BASE_URL "/tweets/%s"
#define TWEET_REPLY_RESTRICTION_URL API_BASE_URL "/tweets/%s/reply-restriction"
#define TWEET_OUTLINE_URL API_BASE_URL "/tweets/%s/outline"

#define SEARCH_USERS_URL API_BASE_URL "/search/users"
#define SEARCH_POSTS_URL API_BASE_URL "/search/posts"

#define NOTIFICATIONS_URL API_BASE_URL "/notifications"
#define NOTIFICATIONS_MARK_ALL_READ_URL API_BASE_URL "/notifications/mark-all-read"
#define NOTIFICATIONS_UNREAD_COUNT_URL API_BASE_URL "/notifications/unread-count"
#define NOTIFICATION_READ_URL API_BASE_URL "/notifications/%s/read"

#define LIKE_TWEET_URL API_BASE_URL "/tweets/%s/like"
#define RETWEET_URL API_BASE_URL "/tweets/%s/retweet"
#define REACTION_URL API_BASE_URL "/tweets/%s/reaction"

#define BOOKMARK_ADD_URL API_BASE_URL "/bookmarks/add"
#define BOOKMARK_REMOVE_URL API_BASE_URL "/bookmarks/remove"
#define BOOKMARKS_LIST_URL API_BASE_URL "/bookmarks"

#define EMOJIS_URL API_BASE_URL "/emojis"

#define DM_CONVERSATIONS_URL API_BASE_URL "/dm/conversations"
#define DM_MESSAGES_URL API_BASE_URL "/dm/conversations/%s"
#define DM_SEND_MESSAGE_URL API_BASE_URL "/dm/conversations/%s/messages"
#define DM_MARK_READ_URL API_BASE_URL "/dm/conversations/%s/read"
#define DM_CREATE_CONVERSATION_URL API_BASE_URL "/dm/conversations"
#define DM_ADD_PARTICIPANTS_URL API_BASE_URL "/dm/conversations/%s/participants"
#define DM_REMOVE_PARTICIPANT_URL API_BASE_URL "/dm/conversations/%s/participants/%s"
#define DM_UPDATE_TITLE_URL API_BASE_URL "/dm/conversations/%s/title"
#define DM_TYPING_URL API_BASE_URL "/dm/conversations/%s/typing"
#define DM_TYPING_STOP_URL API_BASE_URL "/dm/conversations/%s/typing-stop"
#define DM_DRAFT_URL API_BASE_URL "/dm/conversations/%s/draft"
#define DM_DISAPPEARING_URL API_BASE_URL "/dm/conversations/%s/disappearing"
#define DM_INVITE_URL API_BASE_URL "/dm/conversations/%s/invite"
#define DM_INVITE_REVOKE_URL API_BASE_URL "/dm/conversations/%s/invite/revoke"
#define DM_INVITE_JOIN_URL API_BASE_URL "/dm/conversations/join/%s"
#define DM_PERMISSIONS_URL API_BASE_URL "/dm/conversations/%s/permissions"
#define DM_PARTICIPANT_ROLE_URL API_BASE_URL "/dm/conversations/%s/participants/%s/role"
#define DM_PIN_MESSAGE_URL API_BASE_URL "/dm/conversations/%s/pin/%s"
#define DM_PINNED_MESSAGES_URL API_BASE_URL "/dm/conversations/%s/pinned"
#define DM_MESSAGE_REACTIONS_URL API_BASE_URL "/dm/messages/%s/reactions"
#define DM_MESSAGE_EDIT_URL API_BASE_URL "/dm/messages/%s"
#define DM_MESSAGE_DELETE_URL API_BASE_URL "/dm/messages/%s"

#define ADMIN_STATS_URL API_BASE_URL "/admin/stats"
#define ADMIN_USERS_URL API_BASE_URL "/admin/users"
#define ADMIN_POSTS_URL API_BASE_URL "/admin/posts"
#define ADMIN_SUSPENSIONS_URL API_BASE_URL "/admin/suspensions"
#define ADMIN_REPORTS_URL API_BASE_URL "/admin/reports"
#define ADMIN_LOGS_URL API_BASE_URL "/admin/moderation-logs"
#define ADMIN_BLOCKS_URL API_BASE_URL "/admin/blocks"
#define ADMIN_EMOJIS_URL API_BASE_URL "/admin/emojis"
#define ADMIN_BADGES_URL API_BASE_URL "/admin/badges"
#define ADMIN_DMS_URL API_BASE_URL "/admin/dms"
#define ADMIN_DMS_SEARCH_URL API_BASE_URL "/admin/dms/search"
#define ADMIN_SHOP_PRODUCTS_URL API_BASE_URL "/admin/shop/products"
#define ADMIN_SHOP_PURCHASES_URL API_BASE_URL "/admin/shop/purchases"
#define ADMIN_FAKE_NOTIFICATION_URL API_BASE_URL "/admin/fake-notification"
#define ADMIN_TWEETS_URL API_BASE_URL "/admin/tweets"
#define ADMIN_FACT_CHECK_URL API_BASE_URL "/admin/fact-check/%s"

#define CAP_CHALLENGE_URL API_BASE_URL "/auth/cap/challenge"
#define CAP_REDEEM_URL API_BASE_URL "/auth/cap/redeem"
#define CAP_RATE_LIMIT_BYPASS_URL API_BASE_URL "/auth/cap/rate-limit-bypass"

#define PROFILE_URL API_BASE_URL "/profile/%s"
#define PROFILE_FOLLOW_URL API_BASE_URL "/profile/%s/follow"
#define PROFILE_FOLLOWERS_URL API_BASE_URL "/profile/%s/followers"
#define PROFILE_FOLLOWING_URL API_BASE_URL "/profile/%s/following"
#define PROFILE_MUTUALS_URL API_BASE_URL "/profile/%s/mutuals"
#define PROFILE_FOLLOWERS_YOU_KNOW_URL API_BASE_URL "/profile/%s/followers-you-know"
#define PROFILE_POSTS_URL API_BASE_URL "/profile/%s/posts"
#define PROFILE_REPLIES_URL API_BASE_URL "/profile/%s/replies"
#define PROFILE_MEDIA_URL API_BASE_URL "/profile/%s/media"
#define PROFILE_HIGHLIGHTS_URL API_BASE_URL "/profile/%s/highlights"
#define PROFILE_HIGHLIGHT_URL API_BASE_URL "/profile/%s/highlights/%s"
#define PROFILE_NOTIFY_TWEETS_URL API_BASE_URL "/profile/%s/notify-tweets"
#define PROFILE_DELETE_AVATAR_URL API_BASE_URL "/profile/%s/avatar"
#define PROFILE_DELETE_BANNER_URL API_BASE_URL "/profile/%s/banner"
#define PROFILE_PIN_TWEET_URL API_BASE_URL "/profile/%s/pin/%s"
#define PROFILE_PIN_GLOBAL_URL API_BASE_URL "/profile/pin/%s"
#define PROFILE_USERNAME_URL API_BASE_URL "/profile/%s/username"
#define PROFILE_PASSWORD_URL API_BASE_URL "/profile/%s/password"
#define PROFILE_OUTLINES_URL API_BASE_URL "/profile/%s/outlines"
#define PROFILE_DELETE_ACCOUNT_URL API_BASE_URL "/profile/%s"
#define PROFILE_SETTINGS_PRIVATE_URL API_BASE_URL "/profile/settings/private"
#define PROFILE_SETTINGS_TRANSPARENCY_LOCATION_URL API_BASE_URL "/profile/settings/transparency-location"
#define PROFILE_FOLLOW_REQUESTS_URL API_BASE_URL "/profile/follow-requests"
#define PROFILE_FOLLOW_REQUEST_APPROVE_URL API_BASE_URL "/profile/follow-requests/%s/approve"
#define PROFILE_FOLLOW_REQUEST_DENY_URL API_BASE_URL "/profile/follow-requests/%s/deny"
#define PROFILE_AFFILIATE_REQUESTS_URL API_BASE_URL "/profile/affiliate-requests"
#define PROFILE_AFFILIATE_REQUEST_APPROVE_URL API_BASE_URL "/profile/affiliate-requests/%s/approve"
#define PROFILE_AFFILIATE_REQUEST_DENY_URL API_BASE_URL "/profile/affiliate-requests/%s/deny"
#define PROFILE_REQUEST_AFFILIATE_URL API_BASE_URL "/profile/%s/affiliate"
#define PROFILE_AFFILIATES_URL API_BASE_URL "/profile/%s/affiliates"
#define PROFILE_REMOVE_AFFILIATE_URL API_BASE_URL "/profile/remove-affiliate"
#define PROFILE_SETTINGS_COMMUNITY_TAG_URL API_BASE_URL "/profile/settings/community-tag"
#define PROFILE_ALGORITHM_STATS_URL API_BASE_URL "/profile/%s/algorithm-stats"
#define PROFILE_SPAM_SCORE_URL API_BASE_URL "/profile/%s/spam-score"
#define FOLLOWING_TIMELINE_URL API_BASE_URL "/timeline/following"
#define FOR_YOU_INTERESTS_URL API_BASE_URL "/timeline/for-you/interests"
#define FOR_YOU_INTEREST_URL API_BASE_URL "/timeline/for-you/interests/%s"

#define SHOP_USER_URL API_BASE_URL "/mpi/shop/user/%s"
#define SHOP_PRODUCT_URL API_BASE_URL "/mpi/shop/product/%s"
#define SHOP_PRODUCTS_URL API_BASE_URL "/mpi/shop/product"
#define SHOP_PRODUCT_BUY_URL API_BASE_URL "/mpi/shop/product/%s/buy"
#define SHOP_PRODUCT_CONFIRM_URL API_BASE_URL "/mpi/shop/product/%s/confirm"
#define SHOP_PURCHASE_URL API_BASE_URL "/mpi/shop/purchase/%s"
#define MPI_SEND_CREATE_URL API_BASE_URL "/mpi/send/create"
#define MPI_SEND_CONFIRM_URL API_BASE_URL "/mpi/send/confirm"
#define MPI_REQUEST_URL API_BASE_URL "/mpi/request"
#define MPI_REQUEST_PAY_URL API_BASE_URL "/mpi/request/%s/pay"
#define MPI_REQUEST_CONFIRM_URL API_BASE_URL "/mpi/request/%s/confirm"
#define MPI_PAYMENT_BY_MESSAGE_URL API_BASE_URL "/mpi/payments/by-message/%s"

#define PUSH_VAPID_KEY_URL API_BASE_URL "/push/vapid-key"
#define PUSH_SUBSCRIBE_URL API_BASE_URL "/push/subscribe"
#define PUSH_UNSUBSCRIBE_URL API_BASE_URL "/push/unsubscribe"
#define PUSH_STATUS_URL API_BASE_URL "/push/status"

#define BLOCK_USER_URL API_BASE_URL "/blocking/block"
#define UNBLOCK_USER_URL API_BASE_URL "/blocking/unblock"
#define CHECK_BLOCK_URL API_BASE_URL "/blocking/check/%s"
#define MUTE_USER_URL API_BASE_URL "/blocking/mute"
#define UNMUTE_USER_URL API_BASE_URL "/blocking/unmute"
#define CHECK_MUTE_URL API_BASE_URL "/blocking/check-mute/%s"
#define BLOCKING_CAUSES_URL API_BASE_URL "/blocking/causes"

#define POLL_VOTE_URL API_BASE_URL "/tweets/%s/poll/vote"
#define TWEET_POLL_MULTI_VOTE_URL API_BASE_URL "/tweets/%s/poll/multi-vote"

#define UPDATE_PROFILE_URL API_BASE_URL "/profile/%s"
#define UPDATE_AVATAR_URL API_BASE_URL "/profile/%s/avatar"
#define UPDATE_BANNER_URL API_BASE_URL "/profile/%s/banner"

#define UPLOAD_URL API_BASE_URL "/upload/"
#define TENOR_SEARCH_URL API_BASE_URL "/tenor/search"
#define UNSPLASH_SEARCH_URL API_BASE_URL "/unsplash/search"

#define REPORT_CREATE_URL API_BASE_URL "/reports/create"
#define TRANSLATE_URL API_BASE_URL "/translate/"
#define ARTICLES_URL API_BASE_URL "/articles"
#define ARTICLE_DETAILS_URL API_BASE_URL "/articles/%s"
#define DELEGATES_SUMMARY_URL API_BASE_URL "/delegates/summary"
#define DELEGATES_INVITE_URL API_BASE_URL "/delegates/invite"
#define DELEGATE_ACCEPT_URL API_BASE_URL "/delegates/%s/accept"
#define DELEGATE_DECLINE_URL API_BASE_URL "/delegates/%s/decline"
#define DELEGATE_REMOVE_URL API_BASE_URL "/delegates/%s"
#define SCHEDULED_POSTS_URL API_BASE_URL "/scheduled/"
#define SCHEDULED_POST_URL API_BASE_URL "/scheduled/%s"

#define LISTS_URL API_BASE_URL "/lists"
#define LISTS_USER_URL API_BASE_URL "/lists/user/%s"
#define LISTS_CONTAINING_URL API_BASE_URL "/lists/containing/%s"
#define LIST_DETAILS_URL API_BASE_URL "/lists/%s"
#define LIST_TWEETS_URL API_BASE_URL "/lists/%s/tweets"
#define LIST_MEMBERS_URL API_BASE_URL "/lists/%s/members"
#define LIST_MEMBER_URL API_BASE_URL "/lists/%s/members/%s"
#define LIST_FOLLOW_URL API_BASE_URL "/lists/%s/follow"
#define LIST_FOLLOWERS_URL API_BASE_URL "/lists/%s/followers"

#define MUTED_WORDS_URL API_BASE_URL "/muted/words"
#define MUTED_WORD_URL API_BASE_URL "/muted/words/%s"
#define MUTED_WORD_BY_WORD_URL API_BASE_URL "/muted/words/by-word/%s"
#define MUTED_CONVERSATIONS_URL API_BASE_URL "/muted/conversations"
#define MUTED_CONVERSATION_URL API_BASE_URL "/muted/conversations/%s"
#define MUTED_CONVERSATION_STATUS_URL API_BASE_URL "/muted/conversations/%s/status"

#define TRENDS_URL API_BASE_URL "/trends"
#define EXPLORE_BEST_OF_WEEK_URL API_BASE_URL "/explore/best-of-week"
#define EXPLORE_TRENDING_USERS_URL API_BASE_URL "/explore/trending-users"
#define EXPLORE_MOST_BOOKMARKED_URL API_BASE_URL "/explore/most-bookmarked"
#define EXPLORE_MOST_DISCUSSED_URL API_BASE_URL "/explore/most-discussed"
#define EXPLORE_LONGEST_THREADS_URL API_BASE_URL "/explore/longest-threads"
#define EXPLORE_WITH_MEDIA_URL API_BASE_URL "/explore/with-media"
#define EXPLORE_WITH_POLLS_URL API_BASE_URL "/explore/with-polls"
#define EXPLORE_DIGEST_URL API_BASE_URL "/explore/digest"
#define EXPLORE_TOP_HASHTAGS_URL API_BASE_URL "/explore/top-hashtags"
#define EXPLORE_LEADERBOARD_URL API_BASE_URL "/explore/leaderboard"
#define EXPLORE_SUGGESTED_USERS_URL API_BASE_URL "/explore/suggested-users"
#define EXPLORE_DIRECTORY_URL API_BASE_URL "/explore/directory"
#define EXPLORE_USER_ANALYTICS_URL API_BASE_URL "/explore/users/%s/analytics"
#define EXPLORE_USER_COMMON_FOLLOWERS_URL API_BASE_URL "/explore/users/%s/common-followers"
#define EXPLORE_USER_TOP_POSTS_URL API_BASE_URL "/explore/users/%s/top-posts"
#define EXPLORE_STATS_URL API_BASE_URL "/explore/stats"

#define COMMUNITIES_LIST_URL API_BASE_URL "/communities"
#define COMMUNITIES_MY_URL API_BASE_URL "/communities/user/me"
#define COMMUNITIES_SEARCH_URL API_BASE_URL "/communities/search"
#define COMMUNITIES_TRENDING_URL API_BASE_URL "/communities/trending"
#define COMMUNITIES_RECOMMENDED_URL API_BASE_URL "/communities/recommended"
#define COMMUNITY_DETAILS_URL API_BASE_URL "/communities/%s"
#define COMMUNITY_MEMBERS_URL API_BASE_URL "/communities/%s/members"
#define COMMUNITY_MEMBER_ROLE_URL API_BASE_URL "/communities/%s/members/%s/role"
#define COMMUNITY_MEMBER_BAN_URL API_BASE_URL "/communities/%s/members/%s/ban"
#define COMMUNITY_MEMBER_UNBAN_URL API_BASE_URL "/communities/%s/members/%s/unban"
#define COMMUNITY_ACCESS_MODE_URL API_BASE_URL "/communities/%s/access-mode"
#define COMMUNITY_JOIN_REQUESTS_URL API_BASE_URL "/communities/%s/join-requests"
#define COMMUNITY_JOIN_REQUEST_APPROVE_URL API_BASE_URL "/communities/%s/join-requests/%s/approve"
#define COMMUNITY_JOIN_REQUEST_REJECT_URL API_BASE_URL "/communities/%s/join-requests/%s/reject"
#define COMMUNITY_ICON_URL API_BASE_URL "/communities/%s/icon"
#define COMMUNITY_BANNER_URL API_BASE_URL "/communities/%s/banner"
#define COMMUNITY_TAG_URL API_BASE_URL "/communities/%s/tag"
#define COMMUNITY_JOIN_URL API_BASE_URL "/communities/%s/join"
#define COMMUNITY_LEAVE_URL API_BASE_URL "/communities/%s/leave"
#define COMMUNITY_TWEETS_URL API_BASE_URL "/communities/%s/tweets"
#define COMMUNITY_TWEET_PIN_URL API_BASE_URL "/communities/%s/tweets/%s/pin"
#define COMMUNITY_TWEET_UNPIN_URL API_BASE_URL "/communities/%s/tweets/%s/unpin"
#define COMMUNITY_MOD_LOG_URL API_BASE_URL "/communities/%s/mod-log"
#define COMMUNITY_INVITES_URL API_BASE_URL "/communities/%s/invites"
#define COMMUNITY_INVITE_URL API_BASE_URL "/communities/%s/invites/%s"
#define COMMUNITY_INVITE_ACCEPT_URL API_BASE_URL "/communities/invites/%s/accept"
#define USER_COMMUNITIES_URL API_BASE_URL "/users/%s/communities"

#endif /* CONSTANTS_H */
