#include "globals.h"

gchar *g_auth_token = NULL;
gchar *g_current_username = NULL;
gboolean g_is_admin = FALSE;
gboolean g_is_impersonating = FALSE;
gchar *g_impersonation_admin_token = NULL;
gchar *g_impersonation_admin_username = NULL;
gboolean g_impersonation_admin_is_admin = FALSE;
GMutex g_globals_mutex;
GHashTable *g_interaction_cache = NULL;
GtkWidget *g_compose_button = NULL;
GtkWidget *g_header_auth_button = NULL;
GtkWidget *g_notifications_button = NULL;
GtkWidget *g_user_label = NULL;
GtkWidget *g_main_list_box = NULL;
GtkWidget *g_notifications_list = NULL;
GtkWidget *g_conversations_list = NULL;
GtkWidget *g_dm_messages_list = NULL;
GtkWidget *g_dm_title_label = NULL;
GtkWidget *g_dm_info_label = NULL;
GtkWidget *g_dm_entry = NULL;
GtkWidget *g_conversation_list = NULL;
GtkWidget *g_stack = NULL;
GtkWidget *g_back_button = NULL;
GtkWidget *g_admin_button = NULL;

GtkWidget *g_admin_stats_label = NULL;
GtkWidget *g_admin_users_list = NULL;
GtkWidget *g_admin_posts_list = NULL;
GtkWidget *g_admin_suspensions_list = NULL;
GtkWidget *g_admin_reports_list = NULL;
GtkWidget *g_admin_logs_list = NULL;
GtkWidget *g_admin_blocks_list = NULL;
GtkWidget *g_admin_emojis_list = NULL;
GtkWidget *g_admin_badges_list = NULL;
GtkWidget *g_admin_dms_list = NULL;
GtkWidget *g_admin_dm_admin_messages_list = NULL;
GtkWidget *g_admin_shop_products_list = NULL;
GtkWidget *g_admin_shop_purchases_list = NULL;
GtkWidget *g_admin_communities_list = NULL;
GtkWidget *g_admin_users_search = NULL;
GtkWidget *g_admin_posts_search = NULL;
GtkWidget *g_admin_logs_search = NULL;
GtkWidget *g_admin_dms_search = NULL;
GtkWidget *g_admin_shop_search = NULL;
GtkWidget *g_admin_notifications_target_entry = NULL;
GtkWidget *g_admin_notifications_type_entry = NULL;
GtkWidget *g_admin_notifications_title_entry = NULL;
GtkWidget *g_admin_notifications_subtitle_entry = NULL;
GtkWidget *g_admin_notifications_url_entry = NULL;
GtkWidget *g_admin_notifications_message_view = NULL;
GtkWidget *g_admin_notifications_result_label = NULL;
GtkWidget *g_admin_impersonation_entry = NULL;
GtkWidget *g_admin_impersonation_status_label = NULL;
GtkWidget *g_admin_clone_source_entry = NULL;
GtkWidget *g_admin_clone_username_entry = NULL;
GtkWidget *g_admin_clone_name_entry = NULL;
GtkWidget *g_admin_clone_relations_check = NULL;
GtkWidget *g_admin_clone_ghosts_check = NULL;
GtkWidget *g_admin_clone_tweets_check = NULL;
GtkWidget *g_admin_clone_replies_check = NULL;
GtkWidget *g_admin_clone_retweets_check = NULL;
GtkWidget *g_admin_clone_reactions_check = NULL;
GtkWidget *g_admin_clone_communities_check = NULL;
GtkWidget *g_admin_clone_media_check = NULL;
GtkWidget *g_admin_clone_affiliate_check = NULL;
GtkWidget *g_admin_clone_result_label = NULL;
GtkWidget *g_admin_tools_post_targets_entry = NULL;
GtkWidget *g_admin_tools_post_reply_to_entry = NULL;
GtkWidget *g_admin_tools_post_source_entry = NULL;
GtkWidget *g_admin_tools_post_created_at_entry = NULL;
GtkWidget *g_admin_tools_post_no_char_limit_check = NULL;
GtkWidget *g_admin_tools_post_content_view = NULL;
GtkWidget *g_admin_tools_bulk_targets_entry = NULL;
GtkWidget *g_admin_tools_bulk_payload_view = NULL;

GtkWidget *g_search_entry = NULL;
GtkWidget *g_search_users_list = NULL;
GtkWidget *g_search_tweets_list = NULL;

GtkWidget *g_profile_name_label = NULL;
GtkWidget *g_profile_username_label = NULL;
GtkWidget *g_profile_bio_label = NULL;
GtkWidget *g_profile_status_label = NULL;
GtkWidget *g_profile_details_label = NULL;
GtkWidget *g_profile_stats_label = NULL;
GtkWidget *g_profile_avatar_image = NULL;
GtkWidget *g_profile_banner_image = NULL;
GtkWidget *g_profile_badges_box = NULL;
GtkWidget *g_profile_tweets_list = NULL;
GtkWidget *g_profile_replies_list = NULL;
GtkWidget *g_profile_media_list = NULL;
GtkWidget *g_profile_mutuals_list = NULL;
GtkWidget *g_follow_button = NULL;
GtkWidget *g_profile_edit_button = NULL;
GtkWidget *g_profile_notify_button = NULL;
GtkWidget *g_profile_block_button = NULL;
GtkWidget *g_profile_mute_button = NULL;
GtkWidget *g_profile_delete_avatar_button = NULL;
GtkWidget *g_profile_delete_banner_button = NULL;
GtkWidget *g_followers_list = NULL;
GtkWidget *g_following_list = NULL;
struct Profile *g_active_profile = NULL;

GtkWidget *g_bookmarks_list = NULL;

TimelineType g_current_timeline_type = TIMELINE_PUBLIC;

GtkWidget *g_communities_list = NULL;
GtkWidget *g_community_tweets_list = NULL;
GtkWidget *g_community_title_label = NULL;
GtkWidget *g_community_details_label = NULL;
gchar *g_community_id = NULL;

GtkWidget *g_theme_combo = NULL;
GtkWidget *g_compact_mode_switch = NULL;
GtkWidget *g_enable_notifications_switch = NULL;
GtkWidget *g_sound_notifications_switch = NULL;
GtkWidget *g_dm_notifications_switch = NULL;
GtkWidget *g_cache_size_label = NULL;
GtkWidget *g_settings_username_label = NULL;
GtkWidget *g_settings_auth_button = NULL;
GtkWidget *g_change_password_button = NULL;

gboolean g_notifications_enabled = TRUE;
gboolean g_sound_enabled = TRUE;
gboolean g_dm_notifications_enabled = TRUE;
gboolean g_compact_mode_enabled = FALSE;
int g_theme_preference = 2;

/* P2P Encrypted Messaging globals */
GtkWidget *g_p2p_contacts_list = NULL;
GtkWidget *g_p2p_messages_list = NULL;
GtkWidget *g_p2p_entry = NULL;
GtkWidget *g_p2p_title_label = NULL;
GtkWidget *g_p2p_status_label = NULL;
struct P2PSession *g_p2p_session = NULL;
